-- PROCEDURE PARA EXCLUSAO DE CLIENTES. ANTES DE REMOVER CLIENTES, ESTA PROCEDURE REMOVE TODAS AS DEPENDENCIAS DE UM CLIENTE.
CREATE OR REPLACE PROCEDURE EXCLUIR_CLIENTE
  (P_CODEMP INTEGER,
  P_CODCLI INTEGER)
AS 
  V_CODEMP INTEGER;
  V_CODCLI INTEGER;
BEGIN
  /*REMOVENDO OS DADOS DA TABELA FUN_RESPONSAVEL*/
  DELETE FROM FUN_RESPONSAVEL
    WHERE CODCLI = P_CODCLI
      AND CODEMP = P_CODEMP;
  /*REMOVENDO OS DADOS DA TABELA DE LEMBRETE*/      
  DELETE FROM LEMBRETE
    WHERE EXISTS (
      SELECT 1
        FROM ATIVIDADE ATIV
        WHERE LEMBRETE.CODATI = LEMBRETE.CODATI
          AND ATIV.CODEMP = P_CODEMP
          AND ATIV.CODCLI = P_CODCLI
    );
	/*REMOVENDO OS DADOS DA TABELA DE ATIVIDADE.*/
	DELETE FROM ATIVIDADE
	  WHERE CODEMP = P_CODEMP
	    AND CODCLI = P_CODCLI;
    /*REMOVENDO OS DADOS DA TABELA DE CONVIDADO*/
    DELETE FROM CONVIDADO
      WHERE EXISTS (
        SELECT 1
          FROM ATIVIDADE ATIV
          WHERE CONVIDADO.CODATI = ATIV.CODATI
            AND ATIV.CODEMP = P_CODEMP
            AND ATIV.CODCLI = P_CODCLI
      );
      /*REMOVENDO OS DADOS DA TABELA DE CLIENTE.*/
      DELETE FROM CLIENTE
      WHERE CODCLI = P_CODCLI
        AND CODEMP = P_CODEMP;
END;
/